### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/island94-middleman#2]
- [x] Point Cloudflare to current website
- [x] Add www. s3 bucket
- [x] Add Google Analytics
